---
output: github_document
---


```{r}
knitr::opts_chunk$set(message=FALSE)
```

```{r}
library(depmixS4)
library(tidyverse)
library(here)
library(ecp)
```

Write the HMM as a function:

```{r}
#construct the HMM based on Chen et al 2016

hmm <- function(observations){
  mod <- depmix(x~1,data=observations,nstates=2,trstart=runif(4),instart=c(1,0))
  fm <- fit(mod)
  results <- fm@posterior
  results$state <- as.character(results$state)
  bind_cols(observations, results) 
}
```

```{r}
set.seed(12345)
```

Plot figure 3a

```{r}
read.csv("single.csv") %>% 
  hmm() %>% 
  ggplot(aes(t,x, col=state)) + geom_point()+theme_classic() + 
  theme(text = element_text(size = 20)) + 
  labs(subtitle = "(a)")+theme(legend.position = c(0.9, 0.3))
#ggsave(filename="Figure3a.png",width=5,height=(5/8)*5)
ggsave(filename="Figure3a.pdf",width=5,height=(5/8)*5)

```

Run changepoint analysis too, to make Figure 3b

``` {r}
changepoints <- NULL
df <- as.tbl(read.csv("single.csv"))
ECP.res <- e.divisive(df[,2],k=1)
df %>% ggplot(aes(t, x)) + geom_line() + geom_vline(xintercept=ECP.res$estimates[2]*p$t.step, color="blue", size=1) + theme_classic() + 
  theme(text = element_text(size = 20)) + 
  labs(subtitle = "(b)")
#ggsave(filename="Figure3b.png",width=5,height=(5/8)*5)
ggsave(filename="Figure3b.pdf",width=5,height=(5/8)*5)

```

Classify the 100 replicates each individually:

```{r results="hide"}
many_observations <- read_csv("replicates.csv")

## group_by + group_map is just a nice way to apply this function to each replicate:
df <- many_observations %>% 
  group_by(reps) %>% 
  group_map(~ hmm(.x), keep=TRUE) %>% 
  bind_rows()
```

See what it looks like:  

```{r}
df  %>% 
  ggplot(aes(t,x, col=state, group=reps)) + geom_point(alpha=0.2, size=0.1)
```

